config/routes.rb
Rails.application.routes.draw do
  get '/searches' => 'searches#search'
  get '/search' => 'searches#index'
  get '/about' => 'welcome#about'
 
  root 'welcome#index'
  post 'sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'  #This should be delete, but changed to get so use in navbar. 
  resources :shoppers
  resources :products
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :shopper

	def self.price_alert(mobile, desired_price, current_price, product)
		account_sid = ENV['ACCOUNT_SID']
		auth_token = ENV['AUTH_TOKEN']
		@client = Twilio::REST::Client.new account_sid, auth_token
		 
		message = @client.account.messages.create(
		:body => "The price of #{product} has dropped below $#{sprintf "%.2f", desired_price} to $#{sprintf "%.2f", current_price}! -Tracker App",
		:to => "#{mobile}",    
		:from => "+18169120447")   
	end


	
end

app/models/shopper.rb
class Shopper < ActiveRecord::Base
	has_secure_password
	has_many :products

	validates :email,
		presence: true,
		uniqueness: {case_sensitive: false},
		:format => {:with => /\A[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})\z/}

    validates :mobile, numericality: true, length: {minimum: 5}

    validates :password,
		presence: true,
		confirmation: true,
		length: {minimum: 3},
		on: :create

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_shopper, :logged_in?

    def current_shopper
        if session[:current_shopper_id]
            Shopper.find session[:current_shopper_id]
        else
            nil
        end
    end

    def logged_in?
        current_shopper != nil
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ProductsHelper

  def index
  	#@products = Product.all
    @products = current_shopper.products
    respond_to do |format|
      format.html
      format.json { render json: @products }
    end
  end

  def create
    @product = current_shopper.products.new(product_params)
    @product.desired_price = product_params[:price]
    respond_to do |format|
      if @product.save
        format.html{redirect_to products_path}
        format.json{render json: @product}
      else
        format.html{render :new}
        format.json{render json: @product.errors, status: :unprocessable_entity}
      end
    end
    
  end

  def show
    @product = Product.find params[:id]
    more_product_info()
    historical_pricing()
    
  end

  def update
    @product = Product.find(params[:id])
    @product.desired_price = params[:product][:desired_price]
    @product.category = params[:product][:category]
    if @product.save
      render json: @product
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      render json: {}
    else 
      render status: 400, nothing: true
    end
  end

  private
  def product_params
  	params.require(:product).permit(:name, :category, :semantics_id, :photo_url, :price, :desired_price)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	
	def index
		#Displays search page by default.   
	end

	def search
		password = ENV['API_KEY']
		domain = ENV['API_SECRET']  
		sem3 = Semantics3::Products.new(password,domain)		
		sem3.products_field( "search", params["search"] )
		productsHash = sem3.get_products
		# puts "Results of query:\n", productsHash.to_json
		render json: productsHash
	end

	def next
		#Return next 10 results. 
		#Same as before, but want to retrieve the next 10. 
	end

	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
        @shopper = Shopper.find_by :email => params[:email]

        if @shopper.nil?
            flash[:error] = "No such user."

        elsif @shopper.authenticate params[:password]
            session[:current_shopper_id] = @shopper.id
            flash[:notice] = "Thank you for logging in, #{@shopper.email}."

        else
            flash[:error] = "Incorrect password."
        end

        redirect_to root_path
    end

    def destroy
        session[:current_shopper_id] = nil
        flash[:notice] = "You have been logged out."

        redirect_to root_path
    end
end

app/controllers/shoppers_controller.rb
class ShoppersController < ApplicationController
	include ShoppersHelper

	def create
		@shopper = Shopper.new shopper_params
		
		if @shopper.save
            flash[:notice] = "Your account has been created! Please login."
            email = @shopper.email
            mobile = @shopper.mobile
            send_email(email) 
            send_sms(mobile)
            redirect_to root_path
        else
            # Re-render the template that led here. Errors will be displayed
            # because there is a @shopper instance variable now.
            render "welcome/index"
        end
	end

	def update
		@shopper = Shopper.find(params[:id])
	
		if @shopper.update shopper_params
			redirect_to edit_shopper_path(@shopper)
			flash[:notice] = "Your account has been updated!"
		else
			render :edit
		end
		#Put info into database.
	end

	def edit
		@shopper = current_shopper
	end

	def shopper_params
		params.require(:shopper).permit( 
			:password,
			:password_confirmation,
			:email,
			:mobile
			)
	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if logged_in?
  	   redirect_to products_path
  	else
	   render :index
	end 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper

	def more_product_info
		password = ENV['API_KEY']
	    domain = ENV['API_SECRET']
	    sem3 = Semantics3::Products.new(password,domain)
	    semantics_id = @product.semantics_id
	    sem3.products_field( "sem3_id", semantics_id)
	    @product_api = sem3.get_products
	end 

	def historical_pricing
		password = ENV['API_KEY']
	    domain = ENV['API_SECRET']
	    sem3 = Semantics3::Products.new(password,domain)
	    semantics_id = @product.semantics_id
	    sem3.offers_field( "sem3_id", semantics_id)
		@historical_pricing = sem3.get_offers
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shoppers_helper.rb
module ShoppersHelper

	def send_email(email)
			username = 'api'
			password = ENV['MAILGUN_KEY']
			domain = ENV['DOMAIN']
			url = "https://api.mailgun.net/v2/#{domain}/messages"

			params = {
			    :from => "Tracker App <postmaster@#{domain}>",
			    :to => "#{email}",
			    :subject => "WELCOME!",
			    :text => "Welcome to the Tracker App! Login now to search millions of products and start tracking price changes!"
			}

			options = {
			    method: :post,
			    params: params,
			    userpwd: "#{username}:#{password}"
			}

			request = Typhoeus::Request.new(url, options)

			response = request.run()
		end 

		def send_sms(mobile)
			account_sid = ENV['ACCOUNT_SID']
			auth_token = ENV['AUTH_TOKEN']
			@client = Twilio::REST::Client.new account_sid, auth_token
	 
			message = @client.account.messages.create(:body => "Welcome to the Tracker App! Login now to track price changes of millions of products!",
			    :to => "#{mobile}",    
			    :from => "+18169120447")   
		end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link href='http://fonts.googleapis.com/css?family=Play' rel='stylesheet' type='text/css'>
  <title>TrackerApp</title>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script type="text/javascript" src="https://www.google.com/jsapi?autoload={'modules':[{'name':'visualization','version':'1','packages':['corechart']}]}"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>


	<% if current_shopper != nil %>
	<nav class="navbar navbar-inverse" role="navigation">
	<div class="container" id="navbar_fix">
			<div class="navbar-header">
				<a id="home" class="navbar-brand" href="/products"><span class="glyphicon glyphicon-stats"></span> Tracker</a>
				<a class="navbar-brand" href="/search"><span class="glyphicon glyphicon-search"></span> Search</a>
				<a class="navbar-brand" href="/about"><span class="glyphicon glyphicon-info-sign"></span> Info</a>
				<%= link_to 'Settings' , edit_shopper_path(current_shopper), :class => 'navbar-brand', id: "setting"%>
			</div>
		
		<p id="log_out" class="navbar-brand navbar-right"><a href="/logout" class="navbar-link"><span class="glyphicon glyphicon-remove"></span> Logout</a></p>
				
	</div>
	</nav>
	<%else%>
	<nav class="navbar navbar-inverse" role="navigation">
	<div class="container">
		<div class="navbar-header">
				<a id="home" class="navbar-brand" href="/"><span class="glyphicon glyphicon-stats"></span> Tracker</a>
				<a class="navbar-brand" href="/about"><span class="glyphicon glyphicon-info-sign"></span> Info</a>
			</div>
	</div>
	</nav>

	<%end%>



<%= yield %>

<% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
    <% end -%>

</body>
</html>

app/views/products/index.html.erb
<script type="text/javascript">
	var hacky_switch = 1;
</script>

<div class="container">
  	<div class="row">
    	<div class="col-sm-5 products_bar">
    		<div class = "scroll">
				<ul>
					<%@products.each do |product| %>
					<br/>
					<!-- Delete & Show Icons -->
					<div class="my_products" data-product-id="<%=product.id%>" data-overall-id="<%=product.id%>">
						<h4>
							<span class="glyphicon glyphicon-remove product_delete">  </span>
							<a href='/products/<%=product.id%>'><span class="glyphicon glyphicon-eye-open"></a></h4>
					<!-- Panel for name & price: -->
						<div class="panel panel-danger">
							<div class="panel-heading">
						    	<%=product.name%>
						  	</div>
						  	<div class="panel-body">
						  	Price: <%=number_to_currency(product.price)%> <br/>
						  	<img src="<%=product.photo_url%>" height="350" width="350">
						  	</div>
						</div>
					<!-- Panel for category & desired price: -->
						<div class="change_info" data-product-id="<%=product.id%>" data-change-id="<%=product.id%>">
							<div class="panel panel-default">
								<div class="panel-heading">
									<h5 class="change_category">Category: <%=product.category%> </h5>
								</div>
								<div class="panel-body">
									<h5 class="change_price"><span data-plus-id="<%=product.id%>" class="glyphicon glyphicon-plus red_plus"></span> Desired Price: <%=number_to_currency(product.desired_price)%></h5>
								</div>
							</div>
						</div>
					<!-- Hidden form to update products: -->
						<form class="update_product" style="display: none" data-form-id="<%=product.id%>" data-product-id="<%=product.id%>">
							<div class="input-group">
								<span class="input-group-addon">Category:</span>
								<input type="text" class="form-control category" id="category_<%=product.id%>" placeholder="<%=product.category%>">
							</div>

							<br>

							<div class="input-group">
								<span class="input-group-addon"><span class="glyphicon glyphicon-usd"></span></span>
								<input type="text" class="form-control desired_price" id="price_<%=product.id%>" placeholder="<%=product.desired_price%>">
							</div>

							<br/>
							<!-- <button class="btn btn-danger update-btn">Submit</button> -->
							<input type="submit" class="btn btn-danger update-btn"/>
						</form>
					<!-- End of Products View. -->
						<br/>
					</div>
					<% end %>
				</ul>
			</div>
		</div>
		
		<!--CHARTS-->
		<div class="col-sm-7">
			 <div id="piechart"></div>
			 <div id="chart_div"></div>
			 <div id="histopie"></div>
		</div>   
    </div>
</div>

app/views/products/show.html.erb
<script type="text/javascript">
	var show_product = <%= raw @historical_pricing.to_json %>;
</script>

<div class="container" id="product-with-graph">
		<div class="row">
			<div class="col-sm-5 products_bar">

				<div class="panel panel-danger">
					<div class="panel-heading">
				    	<%= @product.name %>
				  	</div>
				  	<div class="panel-body">
				  		<!-- Local Database Results -->
				  		<a href='http://www.amazon.com'><span class="glyphicon glyphicon-shopping-cart"></a>
				  		<img src="<%=@product.photo_url%>" height="425" width="425">
				  		<small>Category: <%=@product.category%> </small>
				  	</div>
				</div>

			  		
			</div>

			<div class="col-sm-7 products_bar">
				<div id="historicalprice"></div>
			</div>

		</div>

		<div class="row">
			<div class="col-sm-5 products_bar">
				<div class="panel panel-danger">
					<h3>Saved Price: <%=number_to_currency(@product.price)%></h3>
			  		<h3>Desired Price: <%=number_to_currency(@product.desired_price)%></h3>
			  		<h3>Current Price: <%=number_to_currency(@product_api["results"][0]["price"])%></h3>
				</div> 		
			</div>
			<div class="col-sm-7 products_bar">
				<div class="panel panel-danger">
			  		<h3>UPC: <%=@product_api["results"][0]["upc"]%></h3>
			  		<h3>Created At: <%=Time.at(@product_api["results"][0]["created_at"]).utc%></h3>
			  		<h3>Model: <%=@product_api["results"][0]["model"]%></h3>
			  		<h3>Product Category: <%=@product_api["results"][0]["category"]%></h3>
			  		<h3>Description: <%=@product_api["results"][0]["description"]%></h3>
			  		<h3>Features: <%=@product_api["results"][0]["features"]["blob"]%></h3>
			  	</div>
			</div>

		</div>

			
		
</div>

app/views/searches/index.html.erb
<div class="container-fluid">

	
		<div class="search_box"><br />
				<h4>
					<span class="glyphicon glyphicon-search"></span> Search Products:
				</h4>
				
				    <input type="text" class="form-control" placeholder="Enter Product Identifier"><br/>
				    			
							      <select class="form-control options" id="search_type">
								      <option>Type of Search</option>
								      <option>Product Name</option>
								      <option>Product Category</option>
								      <option>UPC Search</option>
							      </select>
							      <br/>


					<button id="s" class= "btn btn-danger">
						<span class="glyphicon glyphicon-search"></span>
					</button>
				
	  	</div>


		<div>
			<ul class="results">
			</ul>
		</div>	
	

</div>

app/views/shared/_form_error_list.html.erb
<% if model.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(model.errors.count, "error") %></h2>
        <ul>
            <% model.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shoppers/edit.html.erb
<div class="row">
  <div class="container" id="create_account">
  <h1>Edit Account</h1>
    <%= form_for(@shopper) do |f| %>
      <% if @shopper %>
          <%= render partial: "shared/form_error_list", locals: { model: @shopper } %>
      <% end %>
      <p>
          <%= f.label :email %><br>
          <%= f.text_field :email, class: "form-control" %>
      </p>
      <p>
          <%= f.label :mobile %><br>
          <%= f.text_field :mobile, class: "form-control" %>
      </p>
      <p>
          <%= f.label :password %><br>
          <%= f.password_field :password, class: "form-control" %>
      </p>
      <p>
          <%= f.label :password_confirmation %><br>
          <%= f.password_field :password_confirmation, class: "form-control" %>
      </p>
      <p>
          <%= f.submit class: "btn btn-danger" %>
      </p>
    <% end %>
  </div>  
</div>  

<br/> <br/> <br/> <br/> 

app/views/welcome/_user_forms.html.erb
<div class="row">
  <div class="container" id="create_account">
  <h1>Create Account</h1>
    <%= form_for Shopper.new do |f| %>
      <% if @shopper %>
          <%= render partial: "shared/form_error_list", locals: { model: @shopper } %>
      <% end %>
      <p>
          <%= f.label :email %><br>
          <%= f.text_field :email, class: "form-control" %>
      </p>
      <p>
          <%= f.label :mobile %><br>
          <%= f.text_field :mobile, class: "form-control" %>
      </p>
      <p>
          <%= f.label :password %><br>
          <%= f.password_field :password, class: "form-control" %>
      </p>
      <p>
          <%= f.label :password_confirmation %><br>
          <%= f.password_field :password_confirmation, class: "form-control" %>
      </p>
      <p>
          <%= f.submit class: "btn btn-danger" %>
      </p>
    <% end %>
  </div>  
</div>       
<div class="row" id="bot_row">
  <div class="container" id="bot_container">
    <h1>Already a User?</h1>
      <%= form_tag sessions_path do %>
        <p>
          <%= label_tag :email %><br/>
          <%= text_field_tag :email %>
        </p>
        <p>
          <%= label_tag :password %> <br/>
          <%= password_field_tag :password %>
        </p>
        <p>
          <%= submit_tag "login", class: "btn btn-danger" %>
        </p>
      <% end %> 
  </div>     
</div>

app/views/welcome/about.html.erb
<div class="container">
	<div class="panel panel-danger">
		<div class="panel-heading">
	    	<h1><span class="glyphicon glyphicon-stats"></span> Welcome to the Tracker App!</h1>
	    	<h5><span class="glyphicon glyphicon-search"></span> Sign up for an account and search for all your favorite products online!</h5>
	  	</div>
	  	<div class="panel-body">

	  		<h5><span class="glyphicon glyphicon-warning-sign"></span> Create lists of all items you want to price track. Set a "desired price" to get an SMS/email notification if the price drops below the threshold you set!  Get historical pricing on any item you save. </h5><br/>
	  		<h5><span class="glyphicon glyphicon-shopping-cart"></span> Use Cases:</h5>

			<li> Personal Wish List! You really want it, but are still waiting for the price to drop. </li>
			<li> Holiday Shopping! Sort products into lists to track items for your friends and family. </li>
			<li> Insurance Assessment! Keep track of the current value of all your household products. </li>
	  	
	  	</div>
	</div>



	
	
	

</div>

app/views/welcome/index.html.erb
<%= render partial: "welcome/user_forms" %>